### ISSUE TITLE
ok so i am running this on kali and i have some issues 

### ISSUE THREAD

**Issue by getsecnow** [ehsahil/recon-my-way#1]
root@kali:~/Desktop/bounty/recon-my-way# ruby recon.rb wordlist

Working On --> for example targetip
Resolving Subdomain using Host.
+------------------------------------------------------------------------------------+
ips
ips
sh: 1: Host: not found
Process Finished.

doesnt resolve the hostname 

Dirsearch error 

Dirsearch Started.
+-------------------------------------------------------------------------------------+
54.231.120.161  

Traceback (most recent call last):
  File "dirsearch/./dirsearch.py", line 27, in <module>
    from lib.controller import *
  File "/root/Desktop/bounty/recon-my-way/dirsearch/lib/controller/__init__.py", line 1, in <module>
    from .Controller import *
  File "/root/Desktop/bounty/recon-my-way/dirsearch/lib/controller/Controller.py", line 29, in <module>
    from lib.reports import JSONReport, PlainTextReport, SimpleReport
ModuleNotFoundError: No module named 'lib.reports'
Dirsearch Process Finished.

GoBuster Started. but doesnt provide and results

**Comment by ehsahil** [comment]
Hi @getsecnow, 

You are getting these errors because tools used in `recon.rb` is not properly setup. Please use to the installation guide I provided in `README.md`. 

If the issue is persistence, let me know. 
-Sahil
